# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PTHABasedTsunamiInundationTool
                                 A QGIS plugin
 A QGIS processing plugin that generates tsunami inundation hazard zones using Probabilistic Tsunami Hazard Assessment (PTHA) water levels and coastal digital elevation models.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-10
        copyright            : (C) 2026 by Gaurav
        email                : gaurav.b.khairnar@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PTHABasedTsunamiInundationTool class from file PTHABasedTsunamiInundationTool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .PTHA_Based_Tsunami_Inundation_Tool import PTHABasedTsunamiInundationTool
    return PTHABasedTsunamiInundationTool(iface)
